// 유형 04 그래프를 이용한 수열의 극한.  5번째 값 fig = "쌍페이지시작쪽:L|R:x0,y0,x1,y1" (쌍 이미지 표시좌표, 그림 잘라내기용)
export default [
  ['b', null, '이차함수 $f(x)=2x^2$ 의 그래프 위의 두 점 $\\mathrm{P}(n,\\ f(n))$ 과 $\\mathrm{Q}(n+1,\\ f(n+1))$ 사이의 거리를 $a_n$이라 할 때, $\\lim_{n\\to\\infty}\\frac{a_n}{n}$ 의 값은? (단, $n$은 자연수)', ['1', '2', '3', '4', '5']],
  ['b', null, '곡선 $y=\\sqrt{x}$ 위의 점 $\\mathrm{P}(n,\\ \\sqrt{n})$ 에서 $x$축에 내린 수선의 발을 $\\mathrm{Q}$라 할 때, $\\lim_{n\\to\\infty}\\left(\\overline{\\mathrm{OP}}-\\overline{\\mathrm{OQ}}\\right)$ 의 값은?', ['\\frac{1}{4}', '\\frac{1}{3}', '\\frac{1}{2}', '\\frac{2}{3}', '\\frac{3}{4}'], '26:L:175,555,345,705'],
  ['b', null, '자연수 $n$에 대하여 직선 $x=4$ 가 곡선 $y=\\sqrt{nx}$ 및 $x$축과 만나는 점을 각각 $\\mathrm{P}_n,\\ \\mathrm{Q}_n$ 이라 할 때, $\\lim_{n\\to\\infty}\\sqrt{n}\\left(\\overline{\\mathrm{P}_{n+1}\\mathrm{Q}_{n+1}}-\\overline{\\mathrm{P}_n\\mathrm{Q}_n}\\right)$ 의 값은?', ['\\frac{1}{4}', '\\frac{1}{2}', '1', '2', '4'], '26:L:165,1010,350,1160'],
  ['b', null, '자연수 $n$에 대하여 곡선 $y=\\frac{n}{x}$ 이 직선 $y=\\frac{1}{4}x$ 와 제$1$사분면에서 만나는 점 $\\mathrm{P}_n(x_n,\\ y_n)$ 에 대하여 $l_n=y_{n+1}-y_n$ 이라 할 때, $\\lim_{n\\to\\infty}\\sqrt{n}\\,l_n$ 의 값은?', ['\\frac{1}{4}', '\\frac{1}{2}', '1', '2', '4'], '26:L:620,245,800,425'],
  ['p', '2017학년도 수능', '자연수 $n$에 대하여 직선 $x=4^n$ 이 곡선 $y=\\sqrt{x}$ 와 만나는 점을 $\\mathrm{P}_n$ 이라 하자. 선분 $\\mathrm{P}_n\\mathrm{P}_{n+1}$ 의 길이를 $L_n$ 이라 할 때, $\\lim_{n\\to\\infty}\\left(\\frac{L_{n+1}}{L_n}\\right)^2$ 의 값을 구하시오.', null, '26:L:600,940,810,1115'],
  ['p', '2016학년도 수능', '자연수 $n$에 대하여 좌표가 $(0,\\ 2n+1)$ 인 점을 $\\mathrm{P}$라 하고, 함수 $f(x)=nx^2$ 의 그래프 위의 점 중 $y$좌표가 $1$이고 제$1$사분면에 있는 점을 $\\mathrm{Q}$라 하자. 점 $\\mathrm{R}(0,\\ 1)$ 에 대하여 삼각형 $\\mathrm{PRQ}$ 의 넓이를 $S_n$, 선분 $\\mathrm{PQ}$ 의 길이를 $l_n$ 이라 할 때, $\\lim_{n\\to\\infty}\\frac{S_n^2}{l_n}$ 의 값은?', ['\\frac{3}{2}', '\\frac{5}{4}', '1', '\\frac{3}{4}', '\\frac{1}{2}'], '26:R:1195,285,1380,485'],
  ['p', '2011학년도 모의평가', '좌표평면에서 자연수 $n$에 대하여 기울기가 $n$이고 $y$절편이 양수인 직선이 원 $x^2+y^2=n^2$ 에 접할 때, 이 직선이 $x$축, $y$축과 만나는 점을 각각 $\\mathrm{P}_n,\\ \\mathrm{Q}_n$ 이라 하자. $l_n=\\overline{\\mathrm{P}_n\\mathrm{Q}_n}$ 이라 할 때, $\\lim_{n\\to\\infty}\\frac{l_n}{2n^2}$ 의 값은?', ['\\frac{1}{8}', '\\frac{1}{4}', '\\frac{3}{8}', '\\frac{1}{2}', '\\frac{5}{8}'], '26:R:1195,900,1385,1095'],
  ['p', '2015학년도 모의평가', '자연수 $n$에 대하여 점 $(3n,\\ 4n)$ 을 중심으로 하고 $y$축에 접하는 원 $O_n$ 이 있다. 원 $O_n$ 위를 움직이는 점과 점 $(0,\\ -1)$ 사이의 거리의 최댓값을 $a_n$, 최솟값을 $b_n$ 이라 할 때, $\\lim_{n\\to\\infty}\\frac{a_n}{b_n}$ 의 값을 구하시오.', null],
  ['p', '2013학년도 교육청', '자연수 $n$에 대하여 곡선 $y=\\frac{2n}{x}$ 과 직선 $y=-\\frac{x}{n}+3$ 의 두 교점을 $\\mathrm{A}_n,\\ \\mathrm{B}_n$ 이라 하자. 선분 $\\mathrm{A}_n\\mathrm{B}_n$ 의 길이를 $l_n$ 이라 할 때, $\\lim_{n\\to\\infty}(l_{n+1}-l_n)$ 의 값은?', ['\\frac{1}{2}', '\\frac{\\sqrt{2}}{2}', '1', '\\sqrt{2}', '2'], '26:R:1655,570,1810,720'],
  ['p', '2011학년도 교육청', '$2$ 이상의 자연수 $n$에 대하여 곡선 $y=\\frac{2}{x}$ 와 직선 $y=-x+2n$ 의 두 교점을 $\\mathrm{A}_n,\\ \\mathrm{B}_n$ 이라 하고 선분 $\\mathrm{A}_n\\mathrm{B}_n$ 의 길이를 $l_n$ 이라 할 때, $\\lim_{n\\to\\infty}\\frac{l_n}{n}$ 의 값은?', ['2\\sqrt{2}', '3', '\\sqrt{10}', '2\\sqrt{3}', '4']],
  ['e', null, '자연수 $n$에 대하여 직선 $x=2n$ 이 두 곡선 $y=\\sqrt{x},\\ y=\\sqrt{2x}$ 와 만나는 점을 각각 $\\mathrm{A}_n,\\ \\mathrm{B}_n$ 이라 하자. 선분 $\\mathrm{A}_n\\mathrm{B}_n$ 의 길이를 $l_n$ 이라 할 때, $\\lim_{n\\to\\infty}\\frac{l_{n+1}}{l_n}$ 의 값은?', ['\\frac{1}{2}', '\\frac{\\sqrt{2}}{2}', '1', '\\sqrt{2}', '2'], '28:L:165,325,345,470'],
  ['e', null, '자연수 $n$에 대하여 곡선 $y=\\sqrt{x+1}$ 위의 점 $\\mathrm{P}_n(n,\\ \\sqrt{n+1})$ 에서 $x$축에 내린 수선의 발을 $\\mathrm{Q}_n$ 이라 할 때, $\\lim_{n\\to\\infty}\\left(\\overline{\\mathrm{OP}_n}-\\overline{\\mathrm{OQ}_n}\\right)$ 의 값은? (단, $\\mathrm{O}$는 원점이다.)', ['\\frac{1}{4}', '\\frac{1}{2}', '1', '2', '4']],
  ['e', null, '자연수 $n$에 대하여 곡선 $y=x^2-2nx$ 와 직선 $y=2nx-n^2$ 의 두 교점을 $\\mathrm{P}_n,\\ \\mathrm{Q}_n$ 이라 한다. $\\lim_{n\\to\\infty}\\frac{\\overline{\\mathrm{P}_n\\mathrm{Q}_n}}{n^2}=k$ 일 때, $k^2$ 의 값을 구하여라.', null, '28:L:625,255,795,410'],
  ['e', null, '자연수 $n$에 대하여 곡선 $y=x^2+3x-6$ 과 직선 $y=-x+n$ 이 만나서 생기는 두 점 사이의 거리를 $l_n$ 이라 할 때, $\\lim_{n\\to\\infty}\\frac{l_n^2}{2n}$ 의 값은?', ['4', '5', '6', '7', '8']],
];
