// Country list for the signup form's country field (datalist-backed autocomplete).
// Korean common names are primary since the site defaults to Korean; English names
// are used when the site language is set to English. Not an exhaustive ISO-3166 list,
// but covers all UN member states plus a few commonly-referenced territories.

export const COUNTRIES = [
  { ko: '대한민국', en: 'South Korea' },
  { ko: '미국', en: 'United States' },
  { ko: '캐나다', en: 'Canada' },
  { ko: '영국', en: 'United Kingdom' },
  { ko: '아일랜드', en: 'Ireland' },
  { ko: '프랑스', en: 'France' },
  { ko: '독일', en: 'Germany' },
  { ko: '스위스', en: 'Switzerland' },
  { ko: '오스트리아', en: 'Austria' },
  { ko: '이탈리아', en: 'Italy' },
  { ko: '스페인', en: 'Spain' },
  { ko: '포르투갈', en: 'Portugal' },
  { ko: '네덜란드', en: 'Netherlands' },
  { ko: '벨기에', en: 'Belgium' },
  { ko: '룩셈부르크', en: 'Luxembourg' },
  { ko: '스웨덴', en: 'Sweden' },
  { ko: '노르웨이', en: 'Norway' },
  { ko: '덴마크', en: 'Denmark' },
  { ko: '핀란드', en: 'Finland' },
  { ko: '아이슬란드', en: 'Iceland' },
  { ko: '폴란드', en: 'Poland' },
  { ko: '체코', en: 'Czechia' },
  { ko: '슬로바키아', en: 'Slovakia' },
  { ko: '헝가리', en: 'Hungary' },
  { ko: '루마니아', en: 'Romania' },
  { ko: '불가리아', en: 'Bulgaria' },
  { ko: '그리스', en: 'Greece' },
  { ko: '크로아티아', en: 'Croatia' },
  { ko: '세르비아', en: 'Serbia' },
  { ko: '슬로베니아', en: 'Slovenia' },
  { ko: '보스니아 헤르체고비나', en: 'Bosnia and Herzegovina' },
  { ko: '알바니아', en: 'Albania' },
  { ko: '북마케도니아', en: 'North Macedonia' },
  { ko: '몬테네그로', en: 'Montenegro' },
  { ko: '몰타', en: 'Malta' },
  { ko: '키프로스', en: 'Cyprus' },
  { ko: '우크라이나', en: 'Ukraine' },
  { ko: '벨라루스', en: 'Belarus' },
  { ko: '몰도바', en: 'Moldova' },
  { ko: '러시아', en: 'Russia' },
  { ko: '에스토니아', en: 'Estonia' },
  { ko: '라트비아', en: 'Latvia' },
  { ko: '리투아니아', en: 'Lithuania' },
  { ko: '일본', en: 'Japan' },
  { ko: '중국', en: 'China' },
  { ko: '대만', en: 'Taiwan' },
  { ko: '홍콩', en: 'Hong Kong' },
  { ko: '마카오', en: 'Macau' },
  { ko: '몽골', en: 'Mongolia' },
  { ko: '베트남', en: 'Vietnam' },
  { ko: '태국', en: 'Thailand' },
  { ko: '필리핀', en: 'Philippines' },
  { ko: '인도네시아', en: 'Indonesia' },
  { ko: '말레이시아', en: 'Malaysia' },
  { ko: '싱가포르', en: 'Singapore' },
  { ko: '브루나이', en: 'Brunei' },
  { ko: '미얀마', en: 'Myanmar' },
  { ko: '캄보디아', en: 'Cambodia' },
  { ko: '라오스', en: 'Laos' },
  { ko: '동티모르', en: 'Timor-Leste' },
  { ko: '인도', en: 'India' },
  { ko: '파키스탄', en: 'Pakistan' },
  { ko: '방글라데시', en: 'Bangladesh' },
  { ko: '스리랑카', en: 'Sri Lanka' },
  { ko: '네팔', en: 'Nepal' },
  { ko: '부탄', en: 'Bhutan' },
  { ko: '몰디브', en: 'Maldives' },
  { ko: '아프가니스탄', en: 'Afghanistan' },
  { ko: '카자흐스탄', en: 'Kazakhstan' },
  { ko: '우즈베키스탄', en: 'Uzbekistan' },
  { ko: '투르크메니스탄', en: 'Turkmenistan' },
  { ko: '키르기스스탄', en: 'Kyrgyzstan' },
  { ko: '타지키스탄', en: 'Tajikistan' },
  { ko: '튀르키예', en: 'Türkiye' },
  { ko: '이스라엘', en: 'Israel' },
  { ko: '팔레스타인', en: 'Palestine' },
  { ko: '요르단', en: 'Jordan' },
  { ko: '레바논', en: 'Lebanon' },
  { ko: '시리아', en: 'Syria' },
  { ko: '이라크', en: 'Iraq' },
  { ko: '이란', en: 'Iran' },
  { ko: '사우디아라비아', en: 'Saudi Arabia' },
  { ko: '아랍에미리트', en: 'United Arab Emirates' },
  { ko: '카타르', en: 'Qatar' },
  { ko: '쿠웨이트', en: 'Kuwait' },
  { ko: '바레인', en: 'Bahrain' },
  { ko: '오만', en: 'Oman' },
  { ko: '예멘', en: 'Yemen' },
  { ko: '이집트', en: 'Egypt' },
  { ko: '리비아', en: 'Libya' },
  { ko: '튀니지', en: 'Tunisia' },
  { ko: '알제리', en: 'Algeria' },
  { ko: '모로코', en: 'Morocco' },
  { ko: '수단', en: 'Sudan' },
  { ko: '에티오피아', en: 'Ethiopia' },
  { ko: '케냐', en: 'Kenya' },
  { ko: '탄자니아', en: 'Tanzania' },
  { ko: '우간다', en: 'Uganda' },
  { ko: '르완다', en: 'Rwanda' },
  { ko: '나이지리아', en: 'Nigeria' },
  { ko: '가나', en: 'Ghana' },
  { ko: '세네갈', en: 'Senegal' },
  { ko: '코트디부아르', en: "Côte d'Ivoire" },
  { ko: '카메룬', en: 'Cameroon' },
  { ko: '남아프리카 공화국', en: 'South Africa' },
  { ko: '짐바브웨', en: 'Zimbabwe' },
  { ko: '잠비아', en: 'Zambia' },
  { ko: '모잠비크', en: 'Mozambique' },
  { ko: '앙골라', en: 'Angola' },
  { ko: '콩고민주공화국', en: 'DR Congo' },
  { ko: '호주', en: 'Australia' },
  { ko: '뉴질랜드', en: 'New Zealand' },
  { ko: '피지', en: 'Fiji' },
  { ko: '파푸아뉴기니', en: 'Papua New Guinea' },
  { ko: '멕시코', en: 'Mexico' },
  { ko: '과테말라', en: 'Guatemala' },
  { ko: '벨리즈', en: 'Belize' },
  { ko: '온두라스', en: 'Honduras' },
  { ko: '엘살바도르', en: 'El Salvador' },
  { ko: '니카라과', en: 'Nicaragua' },
  { ko: '코스타리카', en: 'Costa Rica' },
  { ko: '파나마', en: 'Panama' },
  { ko: '쿠바', en: 'Cuba' },
  { ko: '자메이카', en: 'Jamaica' },
  { ko: '도미니카 공화국', en: 'Dominican Republic' },
  { ko: '아이티', en: 'Haiti' },
  { ko: '트리니다드 토바고', en: 'Trinidad and Tobago' },
  { ko: '바하마', en: 'Bahamas' },
  { ko: '브라질', en: 'Brazil' },
  { ko: '아르헨티나', en: 'Argentina' },
  { ko: '칠레', en: 'Chile' },
  { ko: '우루과이', en: 'Uruguay' },
  { ko: '파라과이', en: 'Paraguay' },
  { ko: '볼리비아', en: 'Bolivia' },
  { ko: '페루', en: 'Peru' },
  { ko: '에콰도르', en: 'Ecuador' },
  { ko: '콜롬비아', en: 'Colombia' },
  { ko: '베네수엘라', en: 'Venezuela' },
  { ko: '가이아나', en: 'Guyana' },
  { ko: '수리남', en: 'Suriname' },
  { ko: '기타', en: 'Other' },
];

export function findCountry(value) {
  const query = String(value || '').trim().toLowerCase();
  if (!query) return null;
  return COUNTRIES.find((c) => c.ko.toLowerCase() === query || c.en.toLowerCase() === query) || null;
}

export function isKorea(value) {
  const query = String(value || '').trim().toLowerCase();
  return ['대한민국', '한국', 'south korea', 'korea', 'republic of korea', 'korea, republic of'].includes(query);
}
