export const LANGUAGES = [
  { code: 'ko', label: '한국어', short: 'KO' },
  { code: 'en', label: 'English', short: 'EN' },
  { code: 'zh-CN', label: '简体中文', short: '中文' },
  { code: 'fr', label: 'Français', short: 'FR' },
  { code: 'es', label: 'Español', short: 'ES' },
  { code: 'ja', label: '日本語', short: '日本語' },
  { code: 'ru', label: 'Русский', short: 'RU' },
  { code: 'ar', label: 'العربية', short: 'AR', dir: 'rtl' },
  { code: 'pt', label: 'Português', short: 'PT' },
  { code: 'hi', label: 'हिन्दी', short: 'हिं' },
  { code: 'vi', label: 'Tiếng Việt', short: 'VI' },
  { code: 'id', label: 'Bahasa Indonesia', short: 'ID' },
];

const messages = {
  ko: {
    language: '언어', home: '홈', elementary: '초등', middle: '중등', high: '고등', comingSoon: '준비 중',
    dailyLab: '매일 배움 연구소', heroTitle: '수학부터 코딩까지,\n매일 성장하는 학습 공간', heroDescription: '초등·중등 무작위 수학 문제지를 무료로 제공합니다. 다른 과목과 코딩 실습, 자세한 풀이 콘텐츠도 차례로 추가됩니다.',
    worksheetSettings: '문제지 설정', problemType: '문제 유형', skill: '문제 유형', printPdf: '인쇄 / PDF', answerKey: '답지 보기', worksheet: '문제지 보기', newWorksheet: '새 문제지',
    worksheetId: '문제지 번호', scanQr: 'QR을 스캔하면 같은 문제를 다시 열 수 있어요.', name: '이름', date: '날짜', problems20: '20문제', answers: '정답', answer: '답',
    solveTablet: '태블릿으로 바로 풀기', checkAnswers: '채점하기', correct: '맞았어요', tryAgain: '다시 풀기', score: '20문제 중 {count}문제 정답',
    aboutTutor: '운영자 및 선생님 소개', lessons: '1:1 수학 수업', tutorName: '김채훈', degreeMech: '고려대학교 기계공학 학사', degreeData: '고려대학교 통계학 석사', tutorCurrent: '현재 제주도에서 국제학교 수학강의 / 데이터 분석과 개발자, Audio Electronics Designer로 활동 중', tutorText: '문제 풀이에서 반복되는 실수를 확인하고, 학생별로 필요한 개념과 풀이 습관을 중심으로 수업합니다.', classInquiry: '수업 문의 · 010-3347-0308',
    elementaryTitle: '초등 1~6학년 수학 문제 생성기', elementaryDesc: '학년과 단원을 고르면 매번 새로운 무작위 문제지와 전용 QR 코드가 만들어집니다.',
    primeTitle: '중등 소인수분해 문제 생성기', primeCrumb: '소수와 소인수분해', middleDesc: '유형을 고르면 새로운 20문제 문제지와 정답지가 자동으로 만들어집니다.',
    gcdTitle: '중등 최대공약수·최소공배수 문제 생성기', gcdCrumb: '최대공약수와 최소공배수', integerTitle: '중등 정수와 유리수 문제 생성기', integerCrumb: '정수와 유리수',
    grade1Middle: '중학교 1학년', grade1Short: '중1', worksheetWord: '문제지', answerSheet: '정답지',
    topicElementary: '1~6학년 연산', topicGrade1: '1학년 수 가르기·모으기와 덧셈뺄셈', topicGrade2: '2학년 두 자리 수 계산과 곱셈구구', topicGrade3: '3학년 큰 수 곱셈·나눗셈과 분수', topicGrade4: '4학년 큰 수·분수·소수', topicGrade5: '5학년 약수·분수·소수', topicGrade6: '6학년 나눗셈·비율', topicGeometry: '도형·측정', topicPrime: '소수와 소인수분해', topicGcd: '최대공약수와 최소공배수', topicInteger: '정수와 유리수', topicRationalOps: '유리수의 사칙계산', topicEquation: '일차방정식', topicFactoring: '인수분해', topicQuadratic: '이차함수', topicSequences: '수열', topicLogs: '지수·로그',
  },
  en: {
    language: 'Language', home: 'Home', elementary: 'Elementary', middle: 'Middle School', high: 'High School', comingSoon: 'Coming soon',
    dailyLab: 'Daily Learning Lab', heroTitle: 'From math to coding,\na place to grow every day', heroDescription: 'Free randomized elementary and middle-school math worksheets. More subjects, coding practice, and detailed lessons are coming.',
    worksheetSettings: 'Worksheet settings', problemType: 'Problem type', skill: 'Skill', printPdf: 'Print / PDF', answerKey: 'Answer key', worksheet: 'Worksheet', newWorksheet: 'New worksheet',
    worksheetId: 'Worksheet ID', scanQr: 'Scan the QR code to reopen this worksheet.', name: 'Name', date: 'Date', problems20: '20 problems', answers: 'Answers', answer: 'Answer',
    solveTablet: 'Solve directly on a tablet', checkAnswers: 'Check answers', correct: 'Correct', tryAgain: 'Try again', score: '{count} of 20 correct',
    aboutTutor: 'About the operator & tutor', lessons: '1:1 MATH LESSONS', tutorName: 'Kim Chae-hoon', degreeMech: 'B.S. in Mechanical Engineering, Korea University', degreeData: 'M.S. in Statistics, Korea University', tutorCurrent: 'Currently teaching math at an international school in Jeju, while working as a data analyst/developer and Audio Electronics Designer.', tutorText: 'Lessons identify recurring mistakes and focus on the concepts and solution habits each student needs.', classInquiry: 'Class inquiry · 010-3347-0308',
    elementaryTitle: 'Elementary Math Worksheet Generator', elementaryDesc: 'Choose a grade and topic to create a new random worksheet and QR code.', primeTitle: 'Prime Factorization Worksheet Generator', primeCrumb: 'Primes & Prime Factorization', middleDesc: 'Choose a skill to generate a new 20-question worksheet and answer key.', gcdTitle: 'GCF & LCM Worksheet Generator', gcdCrumb: 'GCF & LCM', integerTitle: 'Integers & Rational Numbers Worksheet Generator', integerCrumb: 'Integers & Rational Numbers', grade1Middle: 'Middle School 1', grade1Short: 'Middle 1', worksheetWord: 'Worksheet', answerSheet: 'Answer Key',
    topicElementary: 'Grades 1–6 Practice', topicGrade1: 'Grade 1: Number Bonds & Addition/Subtraction', topicGrade2: 'Grade 2: Two-Digit Operations & Times Tables', topicGrade3: 'Grade 3: Large-Number Multiplication, Division & Fractions', topicGrade4: 'Grade 4: Large Numbers, Fractions & Decimals', topicGrade5: 'Grade 5: Factors, Fractions & Decimals', topicGrade6: 'Grade 6: Division & Ratios', topicGeometry: 'Geometry & Measurement', topicPrime: 'Primes & Prime Factorization', topicGcd: 'GCF & LCM', topicInteger: 'Integers & Rational Numbers', topicRationalOps: 'Rational Number Operations', topicEquation: 'Linear Equations', topicFactoring: 'Factoring', topicQuadratic: 'Quadratic Functions', topicSequences: 'Sequences', topicLogs: 'Exponents & Logarithms',
  },
  'zh-CN': {
    language: '语言', home: '首页', elementary: '小学', middle: '初中', high: '高中', comingSoon: '即将推出', dailyLab: '每日学习研究所', heroTitle: '从数学到编程，\n每天成长的学习空间', heroDescription: '免费提供小学和初中的随机数学练习题。更多科目、编程练习和详细讲解将陆续推出。', worksheetSettings: '练习设置', problemType: '题型', skill: '题型', printPdf: '打印 / PDF', answerKey: '查看答案', worksheet: '查看练习', newWorksheet: '新练习', worksheetId: '练习编号', scanQr: '扫描二维码可重新打开本练习。', name: '姓名', date: '日期', problems20: '20题', answers: '答案', answer: '答案', solveTablet: '在平板上直接作答', checkAnswers: '检查答案', correct: '正确', tryAgain: '再试一次', score: '20题中答对{count}题', aboutTutor: '关于运营者与老师', lessons: '一对一数学课程', tutorName: '金采勋', degreeMech: '高丽大学机械工程学士', degreeData: '高丽大学统计学硕士', tutorCurrent: '目前在济州岛国际学校教授数学，同时从事数据分析与开发工作，并担任 Audio Electronics Designer。', tutorText: '课程分析反复出现的错误，并针对每位学生所需的概念和解题习惯进行指导。', classInquiry: '课程咨询 · 010-3347-0308', elementaryTitle: '小学数学练习生成器', elementaryDesc: '选择年级和单元，即可生成新的随机练习和专属二维码。', primeTitle: '初中质因数分解练习生成器', primeCrumb: '质数与质因数分解', middleDesc: '选择题型，即可自动生成20道新题及答案。', gcdTitle: '最大公因数与最小公倍数练习生成器', gcdCrumb: '最大公因数与最小公倍数', integerTitle: '整数与有理数练习生成器', integerCrumb: '整数与有理数', grade1Middle: '初中一年级', grade1Short: '初一', worksheetWord: '练习', answerSheet: '答案', topicElementary: '1～6年级运算', topicGrade4: '四年级：大数、分数与小数', topicGrade5: '五年级：因数、分数与小数', topicGrade6: '六年级：除法与比', topicGeometry: '图形与测量', topicPrime: '质数与质因数分解', topicGcd: '最大公因数与最小公倍数', topicInteger: '整数与有理数', topicRationalOps: '有理数的四则运算', topicEquation: '一元一次方程', topicFactoring: '因式分解', topicQuadratic: '二次函数', topicSequences: '数列', topicLogs: '指数与对数',
  },
  fr: {
    language: 'Langue', home: 'Accueil', elementary: 'Primaire', middle: 'Collège', high: 'Lycée', comingSoon: 'Bientôt disponible', dailyLab: "Laboratoire d’apprentissage quotidien", heroTitle: 'Des mathématiques au code,\nun espace pour progresser chaque jour', heroDescription: 'Des fiches de mathématiques aléatoires gratuites pour le primaire et le collège. D’autres matières et activités arriveront bientôt.', worksheetSettings: 'Paramètres de la fiche', problemType: 'Type de problème', skill: 'Compétence', printPdf: 'Imprimer / PDF', answerKey: 'Corrigé', worksheet: 'Fiche', newWorksheet: 'Nouvelle fiche', worksheetId: 'N° de fiche', scanQr: 'Scannez le QR code pour rouvrir cette fiche.', name: 'Nom', date: 'Date', problems20: '20 problèmes', answers: 'Réponses', answer: 'Réponse', solveTablet: 'Répondre directement sur tablette', checkAnswers: 'Vérifier', correct: 'Correct', tryAgain: 'Réessayer', score: '{count} bonnes réponses sur 20', aboutTutor: "À propos de l’enseignant", lessons: 'COURS DE MATHS INDIVIDUELS', tutorName: 'Kim Chae-hoon', degreeMech: 'Licence en génie mécanique, Université de Corée', degreeData: 'Master en statistique, Université de Corée', tutorCurrent: 'Enseigne actuellement les mathématiques dans une école internationale à Jeju, tout en travaillant comme analyste de données/développeur et Audio Electronics Designer.', tutorText: 'Les cours repèrent les erreurs récurrentes et travaillent les notions et méthodes dont chaque élève a besoin.', classInquiry: 'Renseignements · 010-3347-0308', elementaryTitle: 'Générateur de fiches de mathématiques – primaire', elementaryDesc: 'Choisissez un niveau et un thème pour créer une nouvelle fiche aléatoire et son QR code.', primeTitle: 'Générateur – décomposition en facteurs premiers', primeCrumb: 'Nombres premiers et factorisation', middleDesc: 'Choisissez une compétence pour générer 20 nouvelles questions et leur corrigé.', gcdTitle: 'Générateur – PGCD et PPCM', gcdCrumb: 'PGCD et PPCM', integerTitle: 'Générateur – entiers et nombres rationnels', integerCrumb: 'Entiers et rationnels', grade1Middle: '6e / collège', grade1Short: 'Collège', worksheetWord: 'Fiche', answerSheet: 'Corrigé', topicElementary: 'Calcul du CP au CM2', topicGrade4: 'Grands nombres, fractions et décimaux', topicGrade5: 'Diviseurs, fractions et décimaux', topicGrade6: 'Division et rapports', topicGeometry: 'Géométrie et mesures', topicPrime: 'Nombres premiers et factorisation', topicGcd: 'PGCD et PPCM', topicInteger: 'Entiers et rationnels', topicEquation: 'Équations linéaires', topicFactoring: 'Factorisation', topicQuadratic: 'Fonctions quadratiques', topicSequences: 'Suites', topicLogs: 'Exponentielles et logarithmes',
  },
  es: {
    language: 'Idioma', home: 'Inicio', elementary: 'Primaria', middle: 'Secundaria', high: 'Bachillerato', comingSoon: 'Próximamente', dailyLab: 'Laboratorio de Aprendizaje Diario', heroTitle: 'De las matemáticas al código,\nun espacio para crecer cada día', heroDescription: 'Fichas gratuitas y aleatorias de matemáticas para primaria y secundaria. Próximamente habrá más materias y actividades.', worksheetSettings: 'Configuración de la ficha', problemType: 'Tipo de problema', skill: 'Tema', printPdf: 'Imprimir / PDF', answerKey: 'Soluciones', worksheet: 'Ficha', newWorksheet: 'Nueva ficha', worksheetId: 'N.º de ficha', scanQr: 'Escanea el QR para volver a abrir esta ficha.', name: 'Nombre', date: 'Fecha', problems20: '20 problemas', answers: 'Respuestas', answer: 'Respuesta', solveTablet: 'Resolver directamente en una tableta', checkAnswers: 'Comprobar', correct: 'Correcto', tryAgain: 'Inténtalo de nuevo', score: '{count} de 20 correctas', aboutTutor: 'Sobre el profesor', lessons: 'CLASES INDIVIDUALES DE MATEMÁTICAS', tutorName: 'Kim Chae-hoon', degreeMech: 'Grado en Ingeniería Mecánica, Universidad de Corea', degreeData: 'Máster en Estadística, Universidad de Corea', tutorCurrent: 'Actualmente enseña matemáticas en una escuela internacional en Jeju, y trabaja como analista de datos/desarrollador y Audio Electronics Designer.', tutorText: 'Las clases detectan errores recurrentes y trabajan los conceptos y hábitos que necesita cada estudiante.', classInquiry: 'Consulta de clases · 010-3347-0308', elementaryTitle: 'Generador de fichas de matemáticas de primaria', elementaryDesc: 'Elige un curso y un tema para crear una ficha aleatoria y su código QR.', primeTitle: 'Generador de factorización prima', primeCrumb: 'Primos y factorización prima', middleDesc: 'Elige un tema para generar 20 preguntas nuevas y sus soluciones.', gcdTitle: 'Generador de MCD y mcm', gcdCrumb: 'MCD y mcm', integerTitle: 'Generador de enteros y racionales', integerCrumb: 'Enteros y racionales', grade1Middle: '1.º de secundaria', grade1Short: 'Secundaria 1', worksheetWord: 'Ficha', answerSheet: 'Soluciones', topicElementary: 'Cálculo de 1.º a 6.º', topicGrade4: 'Números grandes, fracciones y decimales', topicGrade5: 'Divisores, fracciones y decimales', topicGrade6: 'División y razones', topicGeometry: 'Geometría y medida', topicPrime: 'Primos y factorización prima', topicGcd: 'MCD y mcm', topicInteger: 'Enteros y racionales', topicEquation: 'Ecuaciones lineales', topicFactoring: 'Factorización', topicQuadratic: 'Funciones cuadráticas', topicSequences: 'Sucesiones', topicLogs: 'Exponentes y logaritmos',
  },
  ja: {
    language: '言語', home: 'ホーム', elementary: '小学校', middle: '中学校', high: '高校', comingSoon: '準備中', dailyLab: '毎日学習研究所', heroTitle: '数学からコーディングまで、\n毎日成長できる学習空間', heroDescription: '小学生・中学生向けのランダム数学プリントを無料で提供します。ほかの科目や教材も順次追加します。', worksheetSettings: 'プリント設定', problemType: '問題タイプ', skill: '問題タイプ', printPdf: '印刷 / PDF', answerKey: '解答を見る', worksheet: '問題を見る', newWorksheet: '新しいプリント', worksheetId: 'プリント番号', scanQr: 'QRコードを読み取ると同じプリントを開けます。', name: '名前', date: '日付', problems20: '20問', answers: '解答', answer: '答え', solveTablet: 'タブレットで解く', checkAnswers: '採点する', correct: '正解', tryAgain: 'もう一度', score: '20問中{count}問正解', aboutTutor: '運営者・講師紹介', lessons: 'マンツーマン数学授業', tutorName: 'キム・チェフン', degreeMech: '高麗大学 機械工学 学士', degreeData: '高麗大学 統計学 修士', tutorCurrent: '現在、済州島のインターナショナルスクールで数学を教えながら、データ分析・開発者、Audio Electronics Designerとして活動中。', tutorText: '繰り返しやすいミスを確認し、生徒ごとに必要な概念と解き方を指導します。', classInquiry: '授業のお問い合わせ · 010-3347-0308', elementaryTitle: '小学校算数プリント生成', elementaryDesc: '学年と単元を選ぶと、ランダム問題とQRコードが生成されます。', primeTitle: '中学 素因数分解プリント生成', primeCrumb: '素数と素因数分解', middleDesc: '問題タイプを選ぶと、新しい20問と解答が自動生成されます。', gcdTitle: '最大公約数・最小公倍数プリント生成', gcdCrumb: '最大公約数と最小公倍数', integerTitle: '整数と有理数プリント生成', integerCrumb: '整数と有理数', grade1Middle: '中学1年', grade1Short: '中1', worksheetWord: '問題', answerSheet: '解答', topicElementary: '小1～小6 計算', topicGrade4: '小4 大きな数・分数・小数', topicGrade5: '小5 約数・分数・小数', topicGrade6: '小6 割り算・比', topicGeometry: '図形・測定', topicPrime: '素数と素因数分解', topicGcd: '最大公約数と最小公倍数', topicInteger: '整数と有理数', topicEquation: '一次方程式', topicFactoring: '因数分解', topicQuadratic: '二次関数', topicSequences: '数列', topicLogs: '指数・対数',
  },
  ru: {
    language: 'Язык', home: 'Главная', elementary: 'Начальная школа', middle: 'Средняя школа', high: 'Старшая школа', comingSoon: 'Скоро', dailyLab: 'Лаборатория ежедневного обучения', heroTitle: 'От математики до программирования —\nпространство для ежедневного роста', heroDescription: 'Бесплатные случайные задания по математике для начальной и средней школы. Новые предметы будут добавляться.', worksheetSettings: 'Настройки листа', problemType: 'Тип задания', skill: 'Тема', printPdf: 'Печать / PDF', answerKey: 'Ответы', worksheet: 'Задания', newWorksheet: 'Новый лист', worksheetId: 'Номер листа', scanQr: 'Отсканируйте QR-код, чтобы снова открыть этот лист.', name: 'Имя', date: 'Дата', problems20: '20 заданий', answers: 'Ответы', answer: 'Ответ', solveTablet: 'Решать на планшете', checkAnswers: 'Проверить', correct: 'Верно', tryAgain: 'Попробуйте ещё', score: 'Верно: {count} из 20', aboutTutor: 'О преподавателе', lessons: 'ИНДИВИДУАЛЬНЫЕ УРОКИ МАТЕМАТИКИ', tutorName: 'Ким Чхэ Хун', degreeMech: 'Бакалавр машиностроения, Университет Корё', degreeData: 'Магистр статистики, Университет Корё', tutorCurrent: 'В настоящее время преподаёт математику в международной школе на острове Чеджу, а также работает аналитиком данных/разработчиком и Audio Electronics Designer.', tutorText: 'На занятиях выявляются повторяющиеся ошибки и отрабатываются необходимые каждому ученику понятия и навыки.', classInquiry: 'Запись на занятия · 010-3347-0308', elementaryTitle: 'Генератор заданий по математике для начальной школы', elementaryDesc: 'Выберите класс и тему, чтобы создать новый лист и QR-код.', primeTitle: 'Генератор заданий на разложение на простые множители', primeCrumb: 'Простые числа и факторизация', middleDesc: 'Выберите тему, чтобы создать 20 новых заданий и ответы.', gcdTitle: 'Генератор НОД и НОК', gcdCrumb: 'НОД и НОК', integerTitle: 'Генератор заданий: целые и рациональные числа', integerCrumb: 'Целые и рациональные числа', grade1Middle: '1-й класс средней школы', grade1Short: 'Средняя 1', worksheetWord: 'Задания', answerSheet: 'Ответы', topicElementary: 'Вычисления 1–6 классы', topicGrade4: 'Большие числа, дроби и десятичные', topicGrade5: 'Делители, дроби и десятичные', topicGrade6: 'Деление и отношения', topicGeometry: 'Геометрия и измерения', topicPrime: 'Простые числа и факторизация', topicGcd: 'НОД и НОК', topicInteger: 'Целые и рациональные числа', topicEquation: 'Линейные уравнения', topicFactoring: 'Разложение на множители', topicQuadratic: 'Квадратичные функции', topicSequences: 'Последовательности', topicLogs: 'Степени и логарифмы',
  },
  ar: {
    language: 'اللغة', home: 'الرئيسية', elementary: 'المرحلة الابتدائية', middle: 'المرحلة المتوسطة', high: 'المرحلة الثانوية', comingSoon: 'قريبًا', dailyLab: 'مختبر التعلّم اليومي', heroTitle: 'من الرياضيات إلى البرمجة،\nمساحة للنمو كل يوم', heroDescription: 'أوراق عمل رياضيات عشوائية مجانية للمرحلتين الابتدائية والمتوسطة. ستُضاف مواد أخرى قريبًا.', worksheetSettings: 'إعدادات ورقة العمل', problemType: 'نوع المسألة', skill: 'الموضوع', printPdf: 'طباعة / PDF', answerKey: 'نموذج الإجابة', worksheet: 'ورقة العمل', newWorksheet: 'ورقة جديدة', worksheetId: 'رقم الورقة', scanQr: 'امسح رمز QR لإعادة فتح هذه الورقة.', name: 'الاسم', date: 'التاريخ', problems20: '20 مسألة', answers: 'الإجابات', answer: 'الإجابة', solveTablet: 'الحل مباشرة على الجهاز اللوحي', checkAnswers: 'تحقق من الإجابات', correct: 'صحيح', tryAgain: 'حاول مرة أخرى', score: '{count} إجابة صحيحة من 20', aboutTutor: 'عن المعلّم', lessons: 'دروس رياضيات فردية', tutorName: 'كيم تشاي هون', degreeMech: 'بكالوريوس هندسة ميكانيكية، جامعة كوريا', degreeData: 'ماجستير في الإحصاء، جامعة كوريا', tutorCurrent: 'يعمل حاليًا مدرّس رياضيات في مدرسة دولية في جزيرة جيجو، إلى جانب عمله كمحلل بيانات ومطوّر، ومصمم إلكترونيات صوتية (Audio Electronics Designer).', tutorText: 'تحدد الدروس الأخطاء المتكررة وتركز على المفاهيم وعادات الحل التي يحتاجها كل طالب.', classInquiry: 'للاستفسار عن الدروس · 010-3347-0308', elementaryTitle: 'مولّد أوراق عمل الرياضيات للمرحلة الابتدائية', elementaryDesc: 'اختر الصف والموضوع لإنشاء ورقة عشوائية جديدة ورمز QR.', primeTitle: 'مولّد مسائل التحليل إلى العوامل الأولية', primeCrumb: 'الأعداد الأولية والتحليل', middleDesc: 'اختر موضوعًا لإنشاء 20 مسألة جديدة مع الإجابات.', gcdTitle: 'مولّد القاسم المشترك الأكبر والمضاعف المشترك الأصغر', gcdCrumb: 'ق.م.أ و م.م.أ', integerTitle: 'مولّد مسائل الأعداد الصحيحة والنسبية', integerCrumb: 'الأعداد الصحيحة والنسبية', grade1Middle: 'الصف الأول المتوسط', grade1Short: 'متوسط 1', worksheetWord: 'ورقة عمل', answerSheet: 'الإجابات', topicElementary: 'حساب الصفوف 1–6', topicGrade4: 'الأعداد الكبيرة والكسور والعشريات', topicGrade5: 'القواسم والكسور والعشريات', topicGrade6: 'القسمة والنسب', topicGeometry: 'الهندسة والقياس', topicPrime: 'الأعداد الأولية والتحليل', topicGcd: 'القاسم والمضاعف المشتركان', topicInteger: 'الأعداد الصحيحة والنسبية', topicEquation: 'المعادلات الخطية', topicFactoring: 'التحليل إلى عوامل', topicQuadratic: 'الدوال التربيعية', topicSequences: 'المتتاليات', topicLogs: 'الأسس واللوغاريتمات',
  },
  pt: {
    language: 'Idioma', home: 'Início', elementary: 'Ensino fundamental', middle: 'Ensino médio I', high: 'Ensino médio', comingSoon: 'Em breve', dailyLab: 'Laboratório de Aprendizagem Diária', heroTitle: 'Da matemática à programação,\num espaço para crescer todos os dias', heroDescription: 'Folhas gratuitas e aleatórias de matemática para o ensino fundamental. Mais matérias e atividades serão adicionadas.', worksheetSettings: 'Configurações da folha', problemType: 'Tipo de questão', skill: 'Tema', printPdf: 'Imprimir / PDF', answerKey: 'Gabarito', worksheet: 'Folha', newWorksheet: 'Nova folha', worksheetId: 'N.º da folha', scanQr: 'Leia o QR code para reabrir esta folha.', name: 'Nome', date: 'Data', problems20: '20 questões', answers: 'Respostas', answer: 'Resposta', solveTablet: 'Resolver diretamente no tablet', checkAnswers: 'Verificar respostas', correct: 'Correto', tryAgain: 'Tente novamente', score: '{count} de 20 corretas', aboutTutor: 'Sobre o professor', lessons: 'AULAS INDIVIDUAIS DE MATEMÁTICA', tutorName: 'Kim Chae-hoon', degreeMech: 'Bacharel em Engenharia Mecânica, Universidade da Coreia', degreeData: 'Mestrado em Estatística, Universidade da Coreia', tutorCurrent: 'Atualmente leciona matemática em uma escola internacional em Jeju, além de atuar como analista de dados/desenvolvedor e Audio Electronics Designer.', tutorText: 'As aulas identificam erros recorrentes e trabalham os conceitos e hábitos de resolução de que cada aluno precisa.', classInquiry: 'Informações sobre aulas · 010-3347-0308', elementaryTitle: 'Gerador de folhas de matemática do ensino fundamental', elementaryDesc: 'Escolha o ano e o tema para criar uma nova folha aleatória e seu QR code.', primeTitle: 'Gerador de fatoração em números primos', primeCrumb: 'Números primos e fatoração', middleDesc: 'Escolha um tema para gerar 20 novas questões e o gabarito.', gcdTitle: 'Gerador de MDC e MMC', gcdCrumb: 'MDC e MMC', integerTitle: 'Gerador de inteiros e números racionais', integerCrumb: 'Inteiros e racionais', grade1Middle: '1.º ano do ensino médio I', grade1Short: 'Fundamental II', worksheetWord: 'Folha', answerSheet: 'Gabarito', topicElementary: 'Cálculo do 1.º ao 6.º ano', topicGrade4: 'Números grandes, frações e decimais', topicGrade5: 'Divisores, frações e decimais', topicGrade6: 'Divisão e razões', topicGeometry: 'Geometria e medidas', topicPrime: 'Números primos e fatoração', topicGcd: 'MDC e MMC', topicInteger: 'Inteiros e racionais', topicEquation: 'Equações lineares', topicFactoring: 'Fatoração', topicQuadratic: 'Funções quadráticas', topicSequences: 'Sequências', topicLogs: 'Expoentes e logaritmos',
  },
  hi: {
    language: 'भाषा', home: 'होम', elementary: 'प्राथमिक', middle: 'मध्य विद्यालय', high: 'उच्च विद्यालय', comingSoon: 'जल्द आ रहा है', dailyLab: 'दैनिक अध्ययन प्रयोगशाला', heroTitle: 'गणित से कोडिंग तक,\nहर दिन आगे बढ़ने की जगह', heroDescription: 'प्राथमिक और मध्य विद्यालय के लिए निःशुल्क यादृच्छिक गणित कार्यपत्रक। अन्य विषय जल्द जोड़े जाएंगे।', worksheetSettings: 'कार्यपत्रक सेटिंग', problemType: 'प्रश्न प्रकार', skill: 'विषय', printPdf: 'प्रिंट / PDF', answerKey: 'उत्तर कुंजी', worksheet: 'कार्यपत्रक', newWorksheet: 'नया कार्यपत्रक', worksheetId: 'कार्यपत्रक संख्या', scanQr: 'इस कार्यपत्रक को फिर खोलने के लिए QR कोड स्कैन करें।', name: 'नाम', date: 'तारीख', problems20: '20 प्रश्न', answers: 'उत्तर', answer: 'उत्तर', solveTablet: 'टैबलेट पर सीधे हल करें', checkAnswers: 'उत्तर जाँचें', correct: 'सही', tryAgain: 'फिर प्रयास करें', score: '20 में से {count} सही', aboutTutor: 'शिक्षक के बारे में', lessons: 'व्यक्तिगत गणित कक्षाएँ', tutorName: 'किम चे-हून', degreeMech: 'मैकेनिकल इंजीनियरिंग स्नातक, कोरिया विश्वविद्यालय', degreeData: 'सांख्यिकी में परास्नातक (एम.एस.), कोरिया विश्वविद्यालय', tutorCurrent: 'वर्तमान में जेजू द्वीप के एक अंतरराष्ट्रीय स्कूल में गणित पढ़ाते हैं, साथ ही डेटा विश्लेषक/डेवलपर और Audio Electronics Designer के रूप में सक्रिय हैं।', tutorText: 'कक्षाएँ बार-बार होने वाली गलतियों को पहचानती हैं और हर विद्यार्थी के लिए आवश्यक अवधारणाओं व समाधान की आदतों पर ध्यान देती हैं।', classInquiry: 'कक्षा संबंधी जानकारी · 010-3347-0308', elementaryTitle: 'प्राथमिक गणित कार्यपत्रक जनरेटर', elementaryDesc: 'कक्षा और विषय चुनकर नया यादृच्छिक कार्यपत्रक और QR कोड बनाएँ।', primeTitle: 'अभाज्य गुणनखंड कार्यपत्रक जनरेटर', primeCrumb: 'अभाज्य संख्याएँ और गुणनखंड', middleDesc: 'विषय चुनकर 20 नए प्रश्न और उत्तर कुंजी बनाएँ।', gcdTitle: 'महत्तम समापवर्तक और लघुत्तम समापवर्त्य जनरेटर', gcdCrumb: 'HCF और LCM', integerTitle: 'पूर्णांक और परिमेय संख्या जनरेटर', integerCrumb: 'पूर्णांक और परिमेय संख्याएँ', grade1Middle: 'मध्य विद्यालय कक्षा 1', grade1Short: 'मध्य 1', worksheetWord: 'कार्यपत्रक', answerSheet: 'उत्तर कुंजी', topicElementary: 'कक्षा 1–6 गणना', topicGrade4: 'बड़ी संख्याएँ, भिन्न और दशमलव', topicGrade5: 'गुणनखंड, भिन्न और दशमलव', topicGrade6: 'भाग और अनुपात', topicGeometry: 'ज्यामिति और मापन', topicPrime: 'अभाज्य संख्याएँ और गुणनखंड', topicGcd: 'HCF और LCM', topicInteger: 'पूर्णांक और परिमेय संख्याएँ', topicEquation: 'रैखिक समीकरण', topicFactoring: 'गुणनखंडन', topicQuadratic: 'द्विघात फलन', topicSequences: 'अनुक्रम', topicLogs: 'घातांक और लघुगणक',
  },
  vi: {
    language: 'Ngôn ngữ', home: 'Trang chủ', elementary: 'Tiểu học', middle: 'Trung học cơ sở', high: 'Trung học phổ thông', comingSoon: 'Sắp có', dailyLab: 'Phòng học mỗi ngày', heroTitle: 'Từ toán học đến lập trình,\nkhông gian tiến bộ mỗi ngày', heroDescription: 'Phiếu bài tập toán ngẫu nhiên miễn phí cho tiểu học và trung học cơ sở. Các môn khác sẽ được bổ sung.', worksheetSettings: 'Cài đặt phiếu bài tập', problemType: 'Dạng bài', skill: 'Chủ đề', printPdf: 'In / PDF', answerKey: 'Đáp án', worksheet: 'Bài tập', newWorksheet: 'Phiếu mới', worksheetId: 'Mã phiếu', scanQr: 'Quét mã QR để mở lại phiếu này.', name: 'Họ tên', date: 'Ngày', problems20: '20 câu', answers: 'Đáp án', answer: 'Trả lời', solveTablet: 'Làm trực tiếp trên máy tính bảng', checkAnswers: 'Kiểm tra', correct: 'Đúng', tryAgain: 'Thử lại', score: 'Đúng {count}/20 câu', aboutTutor: 'Giới thiệu giáo viên', lessons: 'HỌC TOÁN 1 KÈM 1', tutorName: 'Kim Chae-hoon', degreeMech: 'Cử nhân Kỹ thuật Cơ khí, Đại học Korea', degreeData: 'Thạc sĩ Thống kê, Đại học Korea', tutorCurrent: 'Hiện đang dạy toán tại một trường quốc tế ở đảo Jeju, đồng thời làm nhà phân tích dữ liệu/nhà phát triển và Audio Electronics Designer.', tutorText: 'Bài học nhận diện lỗi lặp lại và tập trung vào khái niệm cùng thói quen giải bài phù hợp với từng học sinh.', classInquiry: 'Tư vấn lớp học · 010-3347-0308', elementaryTitle: 'Trình tạo phiếu toán tiểu học', elementaryDesc: 'Chọn lớp và chủ đề để tạo phiếu ngẫu nhiên mới cùng mã QR.', primeTitle: 'Trình tạo bài phân tích thừa số nguyên tố', primeCrumb: 'Số nguyên tố và phân tích thừa số', middleDesc: 'Chọn chủ đề để tạo 20 câu mới và đáp án.', gcdTitle: 'Trình tạo ƯCLN và BCNN', gcdCrumb: 'ƯCLN và BCNN', integerTitle: 'Trình tạo bài số nguyên và số hữu tỉ', integerCrumb: 'Số nguyên và số hữu tỉ', grade1Middle: 'Lớp 6', grade1Short: 'THCS', worksheetWord: 'Bài tập', answerSheet: 'Đáp án', topicElementary: 'Phép tính lớp 1–6', topicGrade4: 'Số lớn, phân số và số thập phân', topicGrade5: 'Ước, phân số và số thập phân', topicGrade6: 'Phép chia và tỉ số', topicGeometry: 'Hình học và đo lường', topicPrime: 'Số nguyên tố và phân tích thừa số', topicGcd: 'ƯCLN và BCNN', topicInteger: 'Số nguyên và số hữu tỉ', topicEquation: 'Phương trình bậc nhất', topicFactoring: 'Phân tích nhân tử', topicQuadratic: 'Hàm bậc hai', topicSequences: 'Dãy số', topicLogs: 'Số mũ và logarit',
  },
  id: {
    language: 'Bahasa', home: 'Beranda', elementary: 'Sekolah Dasar', middle: 'Sekolah Menengah', high: 'Sekolah Atas', comingSoon: 'Segera hadir', dailyLab: 'Laboratorium Belajar Harian', heroTitle: 'Dari matematika hingga coding,\nruang untuk berkembang setiap hari', heroDescription: 'Lembar matematika acak gratis untuk sekolah dasar dan menengah. Mata pelajaran lain akan segera ditambahkan.', worksheetSettings: 'Pengaturan lembar', problemType: 'Jenis soal', skill: 'Topik', printPdf: 'Cetak / PDF', answerKey: 'Kunci jawaban', worksheet: 'Lembar soal', newWorksheet: 'Lembar baru', worksheetId: 'Nomor lembar', scanQr: 'Pindai kode QR untuk membuka kembali lembar ini.', name: 'Nama', date: 'Tanggal', problems20: '20 soal', answers: 'Jawaban', answer: 'Jawaban', solveTablet: 'Kerjakan langsung di tablet', checkAnswers: 'Periksa jawaban', correct: 'Benar', tryAgain: 'Coba lagi', score: '{count} dari 20 benar', aboutTutor: 'Tentang pengajar', lessons: 'LES MATEMATIKA PRIVAT', tutorName: 'Kim Chae-hoon', degreeMech: 'Sarjana Teknik Mesin, Korea University', degreeData: 'M.S. Statistika, Korea University', tutorCurrent: 'Saat ini mengajar matematika di sekolah internasional di Pulau Jeju, sekaligus bekerja sebagai analis data/developer dan Audio Electronics Designer.', tutorText: 'Pelajaran mengenali kesalahan berulang dan berfokus pada konsep serta kebiasaan penyelesaian yang dibutuhkan setiap siswa.', classInquiry: 'Informasi kelas · 010-3347-0308', elementaryTitle: 'Pembuat lembar matematika sekolah dasar', elementaryDesc: 'Pilih kelas dan topik untuk membuat lembar acak baru beserta kode QR.', primeTitle: 'Pembuat soal faktorisasi prima', primeCrumb: 'Bilangan prima dan faktorisasi', middleDesc: 'Pilih topik untuk membuat 20 soal baru dan kunci jawaban.', gcdTitle: 'Pembuat FPB dan KPK', gcdCrumb: 'FPB dan KPK', integerTitle: 'Pembuat soal bilangan bulat dan rasional', integerCrumb: 'Bilangan bulat dan rasional', grade1Middle: 'Kelas 7', grade1Short: 'SMP', worksheetWord: 'Lembar soal', answerSheet: 'Kunci jawaban', topicElementary: 'Hitungan kelas 1–6', topicGrade4: 'Bilangan besar, pecahan, dan desimal', topicGrade5: 'Faktor, pecahan, dan desimal', topicGrade6: 'Pembagian dan rasio', topicGeometry: 'Geometri dan pengukuran', topicPrime: 'Bilangan prima dan faktorisasi', topicGcd: 'FPB dan KPK', topicInteger: 'Bilangan bulat dan rasional', topicEquation: 'Persamaan linear', topicFactoring: 'Faktorisasi', topicQuadratic: 'Fungsi kuadrat', topicSequences: 'Barisan', topicLogs: 'Eksponen dan logaritma',
  },
};

const supplementalMessages = {
  ko: { topicAlgebra: '문자와 식', algebraTitle: '중등 문자와 식·일차방정식 문제 생성기', algebraCrumb: '문자와 식·일차방정식', topicCoordinate: '좌표와 그래프', coordinateTitle: '중등 좌표와 그래프 문제 생성기', coordinateCrumb: '좌표와 그래프', topicProportion: '정비례와 반비례', proportionTitle: '중등 정비례와 반비례 문제 생성기', proportionCrumb: '정비례와 반비례',
    navNotices: '공지사항', navContact: '문의하기', noticesTitle: '공지사항', noticesDesc: '사이트의 새로운 소식과 업데이트를 확인하세요.', noticesCrumb: '공지사항', contactTitle: '문의하기', contactDesc: '궁금한 점이나 의견, 오류 제보를 보내주세요.', contactCrumb: '문의하기',
    formName: '이름 (선택)', formEmail: '이메일 (선택, 답장받을 주소)', formType: '문의 유형', formTypeBug: '오류 신고', formTypeSuggestion: '기능 제안', formTypeQuestion: '질문', formTypeOther: '기타', formMessage: '내용', formMessagePlaceholder: '문의하실 내용을 자세히 적어주세요.', formSubmit: '이메일로 보내기', formHelp: '보내기를 누르면 이메일 앱이 열립니다. 내용을 확인하고 전송을 눌러주세요.', formDirectEmail: '또는 직접 이메일 보내기', formRequired: '내용을 입력해주세요.', formSent: '이메일 앱을 열었습니다. 확인 후 전송해주세요.' },
  en: { topicAlgebra: 'Algebraic Expressions', algebraTitle: 'Algebraic Expressions & Linear Equations Generator', algebraCrumb: 'Expressions & Linear Equations', topicCoordinate: 'Coordinates & Graphs', coordinateTitle: 'Coordinate Plane & Graphs Worksheet Generator', coordinateCrumb: 'Coordinates & Graphs', topicProportion: 'Direct & Inverse Proportion', proportionTitle: 'Direct & Inverse Proportion Worksheet Generator', proportionCrumb: 'Direct & Inverse Proportion',
    navNotices: 'Notices', navContact: 'Contact', noticesTitle: 'Notices', noticesDesc: 'Check the latest news and updates for this site.', noticesCrumb: 'Notices', contactTitle: 'Contact', contactDesc: 'Send us your questions, feedback, or bug reports.', contactCrumb: 'Contact',
    formName: 'Name (optional)', formEmail: 'Email (optional, for a reply)', formType: 'Inquiry type', formTypeBug: 'Bug report', formTypeSuggestion: 'Feature suggestion', formTypeQuestion: 'Question', formTypeOther: 'Other', formMessage: 'Message', formMessagePlaceholder: 'Write your message in detail.', formSubmit: 'Send by email', formHelp: 'Pressing send opens your email app. Review the message and hit send there.', formDirectEmail: 'Or email us directly', formRequired: 'Please enter a message.', formSent: 'Your email app has opened. Please review and send.' },
  'zh-CN': { topicAlgebra: '代数式', algebraTitle: '代数式与一元一次方程练习生成器', algebraCrumb: '代数式与一元一次方程', topicCoordinate: '坐标与图象', coordinateTitle: '初中坐标与图象练习生成器', coordinateCrumb: '坐标与图象', topicProportion: '正比例与反比例', proportionTitle: '初中正比例与反比例练习生成器', proportionCrumb: '正比例与反比例',
    navNotices: '公告', navContact: '联系我们', noticesTitle: '公告', noticesDesc: '查看本网站的最新消息与更新。', noticesCrumb: '公告', contactTitle: '联系我们', contactDesc: '欢迎发送您的问题、意见或错误反馈。', contactCrumb: '联系我们',
    formName: '姓名（可选）', formEmail: '邮箱（可选，用于回复）', formType: '咨询类型', formTypeBug: '错误反馈', formTypeSuggestion: '功能建议', formTypeQuestion: '提问', formTypeOther: '其他', formMessage: '内容', formMessagePlaceholder: '请详细描述您的咨询内容。', formSubmit: '通过邮件发送', formHelp: '点击发送后会打开您的邮件应用，请确认内容后发送。', formDirectEmail: '或直接发送邮件', formRequired: '请输入咨询内容。', formSent: '已打开您的邮件应用，请确认后发送。' },
  fr: { topicRationalOps: 'Opérations sur les nombres rationnels', topicAlgebra: 'Calcul littéral', algebraTitle: 'Générateur de calcul littéral et d’équations', algebraCrumb: 'Calcul littéral et équations', topicCoordinate: 'Coordonnées et graphiques', coordinateTitle: 'Générateur – plan cartésien et graphiques', coordinateCrumb: 'Coordonnées et graphiques', topicProportion: 'Proportionnalité directe et inverse', proportionTitle: 'Générateur – proportionnalité directe et inverse', proportionCrumb: 'Proportionnalité directe et inverse',
    navNotices: 'Annonces', navContact: 'Contact', noticesTitle: 'Annonces', noticesDesc: 'Consultez les dernières nouvelles et mises à jour du site.', noticesCrumb: 'Annonces', contactTitle: 'Contact', contactDesc: 'Envoyez-nous vos questions, avis ou signalements de bugs.', contactCrumb: 'Contact',
    formName: 'Nom (facultatif)', formEmail: 'E-mail (facultatif, pour une réponse)', formType: 'Type de demande', formTypeBug: 'Signaler un bug', formTypeSuggestion: 'Suggestion de fonctionnalité', formTypeQuestion: 'Question', formTypeOther: 'Autre', formMessage: 'Message', formMessagePlaceholder: 'Décrivez votre demande en détail.', formSubmit: 'Envoyer par e-mail', formHelp: 'En cliquant sur envoyer, votre application e-mail s’ouvre. Vérifiez le message puis envoyez-le.', formDirectEmail: 'Ou envoyez un e-mail directement', formRequired: 'Veuillez saisir un message.', formSent: 'Votre application e-mail s’est ouverte. Vérifiez puis envoyez.' },
  es: { topicRationalOps: 'Operaciones con números racionales', topicAlgebra: 'Expresiones algebraicas', algebraTitle: 'Generador de expresiones y ecuaciones lineales', algebraCrumb: 'Expresiones y ecuaciones lineales', topicCoordinate: 'Coordenadas y gráficas', coordinateTitle: 'Generador de plano cartesiano y gráficas', coordinateCrumb: 'Coordenadas y gráficas', topicProportion: 'Proporcionalidad directa e inversa', proportionTitle: 'Generador de proporcionalidad directa e inversa', proportionCrumb: 'Proporcionalidad directa e inversa',
    navNotices: 'Anuncios', navContact: 'Contacto', noticesTitle: 'Anuncios', noticesDesc: 'Consulta las últimas noticias y actualizaciones del sitio.', noticesCrumb: 'Anuncios', contactTitle: 'Contacto', contactDesc: 'Envíanos tus preguntas, comentarios o informes de errores.', contactCrumb: 'Contacto',
    formName: 'Nombre (opcional)', formEmail: 'Correo electrónico (opcional, para responder)', formType: 'Tipo de consulta', formTypeBug: 'Informe de error', formTypeSuggestion: 'Sugerencia de función', formTypeQuestion: 'Pregunta', formTypeOther: 'Otro', formMessage: 'Mensaje', formMessagePlaceholder: 'Escribe tu mensaje con detalle.', formSubmit: 'Enviar por correo', formHelp: 'Al enviar se abrirá tu aplicación de correo. Revisa el mensaje y pulsa enviar allí.', formDirectEmail: 'O envía un correo directamente', formRequired: 'Por favor escribe un mensaje.', formSent: 'Se abrió tu aplicación de correo. Revisa y envía.' },
  ja: { topicRationalOps: '有理数の四則計算', topicAlgebra: '文字式', algebraTitle: '文字式・一次方程式プリント生成', algebraCrumb: '文字式と一次方程式', topicCoordinate: '座標とグラフ', coordinateTitle: '中学 座標とグラフ プリント生成', coordinateCrumb: '座標とグラフ', topicProportion: '正比例と反比例', proportionTitle: '中学 正比例と反比例 プリント生成', proportionCrumb: '正比例と反比例',
    navNotices: 'お知らせ', navContact: 'お問い合わせ', noticesTitle: 'お知らせ', noticesDesc: 'サイトの最新情報とアップデートをご確認ください。', noticesCrumb: 'お知らせ', contactTitle: 'お問い合わせ', contactDesc: 'ご質問・ご意見・不具合報告をお送りください。', contactCrumb: 'お問い合わせ',
    formName: 'お名前（任意）', formEmail: 'メールアドレス（任意・返信用）', formType: 'お問い合わせ種類', formTypeBug: '不具合報告', formTypeSuggestion: '機能提案', formTypeQuestion: '質問', formTypeOther: 'その他', formMessage: '内容', formMessagePlaceholder: 'お問い合わせ内容を詳しくご記入ください。', formSubmit: 'メールで送信', formHelp: '送信を押すとメールアプリが開きます。内容を確認して送信してください。', formDirectEmail: 'または直接メールを送る', formRequired: '内容を入力してください。', formSent: 'メールアプリを開きました。内容を確認して送信してください。' },
  ru: { topicRationalOps: 'Действия с рациональными числами', topicAlgebra: 'Алгебраические выражения', algebraTitle: 'Генератор выражений и линейных уравнений', algebraCrumb: 'Выражения и линейные уравнения', topicCoordinate: 'Координаты и графики', coordinateTitle: 'Генератор заданий: координатная плоскость и графики', coordinateCrumb: 'Координаты и графики', topicProportion: 'Прямая и обратная пропорциональность', proportionTitle: 'Генератор заданий: прямая и обратная пропорциональность', proportionCrumb: 'Прямая и обратная пропорциональность',
    navNotices: 'Новости', navContact: 'Контакты', noticesTitle: 'Новости', noticesDesc: 'Следите за последними новостями и обновлениями сайта.', noticesCrumb: 'Новости', contactTitle: 'Контакты', contactDesc: 'Отправьте нам вопросы, отзывы или сообщения об ошибках.', contactCrumb: 'Контакты',
    formName: 'Имя (необязательно)', formEmail: 'Email (необязательно, для ответа)', formType: 'Тип обращения', formTypeBug: 'Сообщить об ошибке', formTypeSuggestion: 'Предложение функции', formTypeQuestion: 'Вопрос', formTypeOther: 'Другое', formMessage: 'Сообщение', formMessagePlaceholder: 'Опишите подробно ваш вопрос.', formSubmit: 'Отправить по почте', formHelp: 'После нажатия откроется ваше почтовое приложение. Проверьте текст и отправьте письмо.', formDirectEmail: 'Или напишите напрямую на email', formRequired: 'Пожалуйста, введите сообщение.', formSent: 'Ваше почтовое приложение открыто. Проверьте и отправьте.' },
  ar: { topicRationalOps: 'عمليات الأعداد النسبية', topicAlgebra: 'العبارات الجبرية', algebraTitle: 'مولّد العبارات الجبرية والمعادلات الخطية', algebraCrumb: 'العبارات والمعادلات الخطية', topicCoordinate: 'الإحداثيات والرسوم البيانية', coordinateTitle: 'مولّد مسائل المستوى الإحداثي والرسوم البيانية', coordinateCrumb: 'الإحداثيات والرسوم البيانية', topicProportion: 'التناسب الطردي والعكسي', proportionTitle: 'مولّد مسائل التناسب الطردي والعكسي', proportionCrumb: 'التناسب الطردي والعكسي',
    navNotices: 'الإعلانات', navContact: 'اتصل بنا', noticesTitle: 'الإعلانات', noticesDesc: 'اطّلع على آخر الأخبار والتحديثات الخاصة بالموقع.', noticesCrumb: 'الإعلانات', contactTitle: 'اتصل بنا', contactDesc: 'أرسل لنا أسئلتك أو ملاحظاتك أو بلاغات الأخطاء.', contactCrumb: 'اتصل بنا',
    formName: 'الاسم (اختياري)', formEmail: 'البريد الإلكتروني (اختياري، للرد)', formType: 'نوع الاستفسار', formTypeBug: 'الإبلاغ عن خطأ', formTypeSuggestion: 'اقتراح ميزة', formTypeQuestion: 'سؤال', formTypeOther: 'أخرى', formMessage: 'الرسالة', formMessagePlaceholder: 'يرجى كتابة رسالتك بالتفصيل.', formSubmit: 'الإرسال عبر البريد الإلكتروني', formHelp: 'عند الضغط على إرسال سيفتح تطبيق البريد لديك. راجع الرسالة ثم أرسلها من هناك.', formDirectEmail: 'أو أرسل بريدًا إلكترونيًا مباشرة', formRequired: 'يرجى إدخال رسالة.', formSent: 'تم فتح تطبيق البريد الإلكتروني. يرجى المراجعة ثم الإرسال.' },
  pt: { topicRationalOps: 'Operações com números racionais', topicAlgebra: 'Expressões algébricas', algebraTitle: 'Gerador de expressões e equações lineares', algebraCrumb: 'Expressões e equações lineares', topicCoordinate: 'Coordenadas e gráficos', coordinateTitle: 'Gerador de plano cartesiano e gráficos', coordinateCrumb: 'Coordenadas e gráficos', topicProportion: 'Proporcionalidade direta e inversa', proportionTitle: 'Gerador de proporcionalidade direta e inversa', proportionCrumb: 'Proporcionalidade direta e inversa',
    navNotices: 'Avisos', navContact: 'Contato', noticesTitle: 'Avisos', noticesDesc: 'Confira as últimas novidades e atualizações do site.', noticesCrumb: 'Avisos', contactTitle: 'Contato', contactDesc: 'Envie suas perguntas, comentários ou relatos de erros.', contactCrumb: 'Contato',
    formName: 'Nome (opcional)', formEmail: 'E-mail (opcional, para resposta)', formType: 'Tipo de contato', formTypeBug: 'Relatar erro', formTypeSuggestion: 'Sugestão de recurso', formTypeQuestion: 'Pergunta', formTypeOther: 'Outro', formMessage: 'Mensagem', formMessagePlaceholder: 'Descreva sua mensagem em detalhes.', formSubmit: 'Enviar por e-mail', formHelp: 'Ao clicar em enviar, seu aplicativo de e-mail será aberto. Revise a mensagem e envie por lá.', formDirectEmail: 'Ou envie um e-mail diretamente', formRequired: 'Por favor, digite uma mensagem.', formSent: 'Seu aplicativo de e-mail foi aberto. Revise e envie.' },
  hi: { topicRationalOps: 'परिमेय संख्याओं पर संक्रियाएँ', topicAlgebra: 'बीजीय व्यंजक', algebraTitle: 'बीजीय व्यंजक और रैखिक समीकरण जनरेटर', algebraCrumb: 'व्यंजक और रैखिक समीकरण', topicCoordinate: 'निर्देशांक और आलेख', coordinateTitle: 'निर्देशांक तल और आलेख जनरेटर', coordinateCrumb: 'निर्देशांक और आलेख', topicProportion: 'सीधा और व्युत्क्रम समानुपात', proportionTitle: 'सीधा और व्युत्क्रम समानुपात जनरेटर', proportionCrumb: 'सीधा और व्युत्क्रम समानुपात',
    navNotices: 'सूचनाएँ', navContact: 'संपर्क करें', noticesTitle: 'सूचनाएँ', noticesDesc: 'साइट की नवीनतम खबरें और अपडेट देखें।', noticesCrumb: 'सूचनाएँ', contactTitle: 'संपर्क करें', contactDesc: 'अपने सवाल, सुझाव या बग रिपोर्ट भेजें।', contactCrumb: 'संपर्क करें',
    formName: 'नाम (वैकल्पिक)', formEmail: 'ईमेल (वैकल्पिक, जवाब के लिए)', formType: 'अनुरोध का प्रकार', formTypeBug: 'बग रिपोर्ट', formTypeSuggestion: 'सुझाव', formTypeQuestion: 'प्रश्न', formTypeOther: 'अन्य', formMessage: 'संदेश', formMessagePlaceholder: 'कृपया अपना संदेश विस्तार से लिखें।', formSubmit: 'ईमेल से भेजें', formHelp: 'भेजें दबाने पर आपका ईमेल ऐप खुलेगा। संदेश जाँचकर वहाँ से भेजें।', formDirectEmail: 'या सीधे ईमेल भेजें', formRequired: 'कृपया संदेश दर्ज करें।', formSent: 'आपका ईमेल ऐप खुल गया है। जाँचकर भेजें।' },
  vi: { topicRationalOps: 'Phép tính với số hữu tỉ', topicAlgebra: 'Biểu thức đại số', algebraTitle: 'Trình tạo biểu thức và phương trình bậc nhất', algebraCrumb: 'Biểu thức và phương trình bậc nhất', topicCoordinate: 'Tọa độ và đồ thị', coordinateTitle: 'Trình tạo bài mặt phẳng tọa độ và đồ thị', coordinateCrumb: 'Tọa độ và đồ thị', topicProportion: 'Tỉ lệ thuận và tỉ lệ nghịch', proportionTitle: 'Trình tạo bài tỉ lệ thuận và tỉ lệ nghịch', proportionCrumb: 'Tỉ lệ thuận và tỉ lệ nghịch',
    navNotices: 'Thông báo', navContact: 'Liên hệ', noticesTitle: 'Thông báo', noticesDesc: 'Xem tin tức và cập nhật mới nhất của trang web.', noticesCrumb: 'Thông báo', contactTitle: 'Liên hệ', contactDesc: 'Gửi câu hỏi, góp ý hoặc báo lỗi cho chúng tôi.', contactCrumb: 'Liên hệ',
    formName: 'Tên (không bắt buộc)', formEmail: 'Email (không bắt buộc, để nhận phản hồi)', formType: 'Loại yêu cầu', formTypeBug: 'Báo lỗi', formTypeSuggestion: 'Đề xuất tính năng', formTypeQuestion: 'Câu hỏi', formTypeOther: 'Khác', formMessage: 'Nội dung', formMessagePlaceholder: 'Vui lòng mô tả chi tiết nội dung.', formSubmit: 'Gửi qua email', formHelp: 'Khi nhấn gửi, ứng dụng email sẽ mở ra. Kiểm tra nội dung rồi gửi từ đó.', formDirectEmail: 'Hoặc gửi email trực tiếp', formRequired: 'Vui lòng nhập nội dung.', formSent: 'Ứng dụng email của bạn đã mở. Vui lòng kiểm tra rồi gửi.' },
  id: { topicRationalOps: 'Operasi bilangan rasional', topicAlgebra: 'Bentuk aljabar', algebraTitle: 'Pembuat bentuk aljabar dan persamaan linear', algebraCrumb: 'Bentuk aljabar dan persamaan linear', topicCoordinate: 'Koordinat dan Grafik', coordinateTitle: 'Pembuat soal bidang koordinat dan grafik', coordinateCrumb: 'Koordinat dan Grafik', topicProportion: 'Perbandingan Senilai dan Berbalik Nilai', proportionTitle: 'Pembuat soal perbandingan senilai dan berbalik nilai', proportionCrumb: 'Perbandingan Senilai dan Berbalik Nilai',
    navNotices: 'Pengumuman', navContact: 'Kontak', noticesTitle: 'Pengumuman', noticesDesc: 'Lihat berita dan pembaruan terbaru situs ini.', noticesCrumb: 'Pengumuman', contactTitle: 'Kontak', contactDesc: 'Kirim pertanyaan, masukan, atau laporan bug kepada kami.', contactCrumb: 'Kontak',
    formName: 'Nama (opsional)', formEmail: 'Email (opsional, untuk balasan)', formType: 'Jenis pertanyaan', formTypeBug: 'Laporan bug', formTypeSuggestion: 'Saran fitur', formTypeQuestion: 'Pertanyaan', formTypeOther: 'Lainnya', formMessage: 'Pesan', formMessagePlaceholder: 'Tuliskan pesan Anda secara rinci.', formSubmit: 'Kirim lewat email', formHelp: 'Menekan kirim akan membuka aplikasi email Anda. Periksa pesan lalu kirim dari sana.', formDirectEmail: 'Atau kirim email langsung', formRequired: 'Silakan isi pesan.', formSent: 'Aplikasi email Anda telah terbuka. Periksa lalu kirim.' },
};

export function tr(language, key, vars = {}) {
  const template = messages[language]?.[key] ?? supplementalMessages[language]?.[key] ?? messages.en[key] ?? messages.ko[key] ?? key;
  return Object.entries(vars).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, value), template);
}

export function isRtl(language) { return language === 'ar'; }
export function isNonKorean(language) { return language !== 'ko'; }
