// 기하와 벡터 유형별 기출 카탈로그 빌드.
//   node scripts/build_jjang_geo_catalog.mjs            -> 검증만
//   node scripts/build_jjang_geo_catalog.mjs --write    -> functions/api/jjang-geo/_data/catalog.js + D1 SQL(out/geo_sql)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ANSWER_KEY, EXPECTED_COUNTS } from './jjang_geo_src/answerKey.mjs';
import { TYPES, BOUNDS, SOURCES, solPageForIdx } from './jjang_geo_src/meta.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const srcDir = path.join(here, 'jjang_geo_src');
const outDir = path.join(srcDir, 'out');
const segments = JSON.parse(fs.readFileSync(path.join(outDir, 'geo_segments.json'), 'utf8'));
const SECTION = { b: '기본문제', p: '기출문제', e: '예상문제' };

const problems = [];
for (const [typeNo, meta] of Object.entries(TYPES)) {
  const t = Number(typeNo);
  const key = ANSWER_KEY[t];
  const segs = segments.filter((s) => s.type === t);
  if (segs.length !== EXPECTED_COUNTS[t] || key.length !== EXPECTED_COUNTS[t]) throw new Error(`type ${t}: segments ${segs.length}, key ${key.length}, expected ${EXPECTED_COUNTS[t]}`);
  const [pStart, eStart] = BOUNDS[t];
  segs.forEach((seg, i) => {
    const n = i + 1;
    const code = n < pStart ? 'b' : n >= eStart ? 'e' : 'p';
    const source = SOURCES[t][n] || null;
    if (code === 'p' && !source) throw new Error(`type ${t} #${n}: 기출 without source`);
    if (code !== 'p' && source) throw new Error(`type ${t} #${n}: source on non-기출`);
    const k = key[i];
    if (k.kind === 'mc' && (k.value < 1 || k.value > 5)) throw new Error(`type ${t} #${n}: bad choice`);
    const m = source ? source.match(/^(\d{4})학년도\s*(.+)$/) : null;
    problems.push({
      id: `jg-${String(t).padStart(2, '0')}-${String(n).padStart(2, '0')}`,
      typeNo: t, typeId: meta.id, typeName: meta.name, number: n,
      section: SECTION[code], sectionCode: code,
      source, examYear: m ? Number(m[1]) : null, examKind: m ? m[2] : null,
      kind: k.kind === 'mc' ? 'mcq' : 'short', answer: String(k.value),
      image: `geo-${String(t).padStart(2, '0')}-${String(n).padStart(2, '0')}`,
      solPage: solPageForIdx(seg.idx),
    });
  });
}
const typeList = Object.entries(TYPES).map(([no, t]) => ({
  no: Number(no), ...t,
  counts: ['b', 'p', 'e'].map((c) => problems.filter((p) => p.typeNo === Number(no) && p.sectionCode === c).length),
}));
console.log(`problems=${problems.length}`, typeList.map((t) => `${t.no}:${t.counts.join('/')}`).join(' '));

if (process.argv.includes('--write')) {
  const dataDir = path.join(here, '..', 'functions', 'api', 'jjang-geo', '_data');
  fs.mkdirSync(dataDir, { recursive: true });
  fs.writeFileSync(path.join(dataDir, 'catalog.js'), `// generated by scripts/build_jjang_geo_catalog.mjs --write\nexport default ${JSON.stringify({ types: typeList, problems })};\n`);

  const assets = [];
  for (const p of problems) assets.push([p.image, fs.readFileSync(path.join(outDir, 'geo_problems', `${p.image}.png`)).toString('base64')]);
  for (const f of fs.readdirSync(path.join(outDir, 'gsol')).sort()) {
    const m = f.match(/^gsol-(\d+)\.png$/);
    if (m) assets.push([`gsol-${m[1]}`, fs.readFileSync(path.join(outDir, 'gsol', f)).toString('base64')]);
  }
  const sqlDir = path.join(outDir, 'geo_sql');
  fs.rmSync(sqlDir, { recursive: true, force: true });
  fs.mkdirSync(sqlDir, { recursive: true });
  let chunk = []; let size = 0; let n = 0;
  const flush = () => {
    if (!chunk.length) return;
    fs.writeFileSync(path.join(sqlDir, `assets-${String(n).padStart(2, '0')}.sql`), chunk.join('\n') + '\n');
    n += 1; chunk = []; size = 0;
  };
  const PIECE = 80000; // D1 rejects statements over ~100KB
  for (const [id, b64] of assets) {
    const stmts = [];
    for (let i = 0; i < b64.length; i += PIECE) {
      const piece = b64.slice(i, i + PIECE);
      stmts.push(i === 0
        ? `INSERT OR REPLACE INTO jjang_calc1_assets (id, mime, data) VALUES ('${id}', 'image/png', '${piece}');`
        : `UPDATE jjang_calc1_assets SET data = data || '${piece}' WHERE id = '${id}';`);
    }
    const total = stmts.reduce((a, s) => a + s.length, 0);
    if (size + total > 600000 && chunk.length) flush();
    chunk.push(...stmts); size += total;
  }
  flush();
  console.log(`catalog written; assets ${assets.length} -> ${n} sql files`);
}
